name: qoi_dart
description: A QOI image encoder / decoder implemented purely in dart
version: 1.0.2
homepage: https://github.com/grontol/qoi_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
